### ISSUE TITLE
Incorporate pH-charging of SMILES

### ISSUE THREAD

**Issue by kjemist** [moldescriptor/molecule-descriptors-webtool#4]
### Description
This function will give users the option to charge the input SMILES according to a specified pH-value

### Feature Request
Add this script: https://github.com/kjemist/compound_preparation/tree/master/scripts to the backend of MolDescriptor. Usage is described in the ReadMe file.
Users should be able to specify if they want to charge their structures. If selected, the following parameters should be set:

- **pH:** (float) the desired pH. min: 0, max: 14 (theoretically, we can go higher/lower). Default: 7.0. In the script, this parameter is passed as -p
- **range:** (float) The desired pH range. example:  if 1.5,  means we go from pH 5.5 to 8.5.  In the script, this parameter is passed as -r

The output may output multiple structures. If that is the case, descriptors for both SMILES should be calculated

**Comment by johlys** [comment]
Completed in #22
